### ISSUE TITLE
G28 and G29 are executing 3 times

### ISSUE THREAD

**Issue by tlee28VT** [Stephan3/dwc2-for-klipper-socket#10]
Just as the title says, G28 and G29 are running twice whenever I run them. This happens after a HTTP request timed out notification for both.

**Comment by Stephan3** [comment]
pleas read the readme, its written in fat letters

**Comment by sixtyfive** [comment]
I experienced the same problem, read the README multiple times, looked at Issues and Pull Requests, googled around, nothing. Only when I got the idea to also look at Closed Issues did I find this one here and understood _why_ the README talks about AJAX Retries. It might be helpful to newcomers, to rephrase a little (i.e., include the word "thrice"!) or have a little section on Troubleshooting.
