### ISSUE TITLE
temperature notification

### ISSUE THREAD

**Issue by Matou25** [Stephan3/dwc2-for-klipper-socket#13]
hi,

During print , i have temperature notification and msg in console 
is it possible to disabled it ?

**Comment by Stephan3** [comment]
This is a typical klipper behavior. You can use regex filters in DWC configfile to filter it.

**Comment by Matou25** [comment]
thx 

i wil take a look for a regex

**Comment by sancrum** [comment]
> thx
> 
> i wil take a look for a regex

Any luck?

Nevermind. 
I've opened ~/klipper/klippy/extras/heaters.py and commented three lines:
![spam](https://user-images.githubusercontent.com/40698835/95692084-b5048a00-0c2c-11eb-9a82-ebd1fb5034e1.jpg)

It's dirty trick, I know.
